name: obfuscate-on-dispatch
on:
  workflow_dispatch:
  repository_dispatch:
    types: [prometheus-obfuscate]

jobs:
  obfuscate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: install luajit
        run: sudo apt-get update && sudo apt-get install -y luajit

      - name: run runner.lua
        env:
          USER_CODE: ${{ github.event.client_payload.code || '' }}
          PROM_PRESET: ${{ github.event.client_payload.preset || 'Strong' }}
        run: |
          chmod +x ./runner.lua || true
          luajit ./runner.lua > obfuscated.txt
          cat obfuscated.txt

      - name: commit obfuscated file
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add obfuscated.txt
          git commit -m "obfuscate: run by workflow" || echo "no changes"
          git push origin HEAD:${{ github.ref_name || 'main' }} || echo "push failed"
