# .github/workflows/obfuscate.yml

name: obfuscate-on-dispatch
on:
  repository_dispatch:
    types: [prometheus-obfuscate]

jobs:
  obfuscate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: install luajit and luarocks
        run: |
          sudo apt-get update
          sudo apt-get install -y luajit luarocks
          # Install the Lua MongoDB driver
          sudo luarocks install lua-mongo
          
      - name: run obfuscator and write to DB
        env:
          USER_CODE: ${{ github.event.client_payload.code || '' }}
          PROM_PRESET: ${{ github.event.client_payload.preset || 'Strong' }}
          JOB_ID: ${{ github.event.client_payload.job_id || '' }}
          # Pass the MongoDB secret for the Lua script to use
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: |
          chmod +x ./runner.lua || true
          # Note: We will rename runner.lua to a new script, like db_runner.lua,
          # or simply update runner.lua to include the DB logic.
          luajit ./runner.lua
          
      # Remove the 'commit obfuscated file' step completely!
