# .github/workflows/obfuscate.yml
name: obfuscate-on-dispatch
on:
  repository_dispatch:
    types: [prometheus-obfuscate]

jobs:
  obfuscate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: install dependencies
        run: |
          sudo apt-get update
          
          # Install LuaJIT, LuaRocks, C build essentials, and MongoDB C dependencies
          sudo apt-get install -y luajit luarocks build-essential libbson-dev libmongoc-dev
          
          # Install the Lua MongoDB driver rock
          sudo luarocks install lua-mongo
          
      - name: run obfuscator and write to DB (Final Path Fix)
        env:
          USER_CODE: ${{ github.event.client_payload.code || '' }}
          PROM_PRESET: ${{ github.event.client_payload.preset || 'Strong' }}
          JOB_ID: ${{ github.event.client_payload.job_id || '' }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: |
          chmod +x ./runner.lua || true
          
          # CRITICAL FINAL PATH FIX: 
          # We explicitly chain the path setup and the execution using '&&'. 
          # This guarantees that the LUA_PATH/LUA_CPATH variables are set 
          # by 'eval $(luarocks path)' and are immediately available to 'luajit'.
          eval $(luarocks path) && luajit ./runner.lua

