name: Prometheus Job Processor
on:
  repository_dispatch:
    types: [obfuscate_code] # 🎯 FIXED: This must match the event Vercel sends

jobs:
  obfuscate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y luajit jq

      - name: Run Obfuscator
        id: run_obfuscator
        env:
          # Using client_payload variables from the reverted file
          USER_CODE: ${{ github.event.client.payload.code || '' }} 
          PROM_PRESET: ${{ github.event.client.payload.preset || 'Strong' }}
        run: |
          chmod +x ./runner.lua || true
          
          OUTPUT=$(luajit ./runner.lua 2> stderr.log)
          
          echo "exit_code=$?" >> $GITHUB_ENV

          # --- FIX: Robustly set multiline 'result' output ---
          DELIMITER_RESULT=$(openssl rand -hex 16)
          echo "result<<$DELIMITER_RESULT" >> $GITHUB_OUTPUT
          echo "$OUTPUT" >> $GITHUB_OUTPUT
          echo "$DELIMITER_RESULT" >> $GITHUB_OUTPUT
          
          # --- FIX: Robustly set multiline 'error_log' output ---
          DELIMITER_ERROR=$(openssl rand -hex 16)
          echo "error_log<<$DELIMITER_ERROR" >> $GITHUB_OUTPUT
          cat stderr.log >> $GITHUB_OUTPUT
          echo "$DELIMITER_ERROR" >> $GITHUB_OUTPUT

      - name: Report Success to Vercel
        if: env.exit_code == 0
        env:
          JOB_ID: ${{ github.event.client.payload.job_id }}
          VERCEL_WEBHOOK_URL: ${{ secrets.VERCEL_COMPLETE_URL }} 
          WORKER_SECRET: ${{ secrets.WORKER_SECRET }}
          OBFUSCATED_CODE: ${{ steps.run_obfuscator.outputs.result }}
        run: |
          # Sanitize and export to ensure clean variables
          export VERCEL_WEBHOOK_URL="$(printf '%s' "$VERCEL_WEBHOOK_URL" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
          export WORKER_SECRET="$(printf '%s' "$WORKER_SECRET" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
          
          echo "--- DIAGNOSTIC START ---"
          # CRITICAL CHECK: Is the jobId being received?
          printf "JOB_ID_RECEIVED: %.50s\n" "$JOB_ID" 
          echo "VERCEL_URL_LENGTH: ${#VERCEL_WEBHOOK_URL}"
          echo "WORKER_SECRET_START: ${WORKER_SECRET:0:8}"
          echo "--- DIAGNOSTIC END ---"
          
          # 1. Write the massive code string to a temporary file
          echo "$OBFUSCATED_CODE" > obfuscated_code.txt

          # 2. Use 'jq --rawfile' to read the file content safely into the JSON object
          jq -n \
            --arg jid "$JOB_ID" \
            --rawfile code obfuscated_code.txt \
            '{ "jobId": $jid, "status": "COMPLETED", "obfuscatedCode": $code, "error": null }' > payload.json
          
          # 3. Use curl to read the data directly from the file using the '@' prefix
          curl -f -X POST "$VERCEL_WEBHOOK_URL" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $WORKER_SECRET" \
            --data-binary @payload.json # 🎯 FIXED: Use --data-binary for files

      - name: Report Failure to Vercel
        if: env.exit_code != 0
        env:
          JOB_ID: ${{ github.event.client.payload.job_id }}
          VERCEL_WEBHOOK_URL: ${{ secrets.VERCEL_COMPLETE_URL }}
          WORKER_SECRET: ${{ secrets.WORKER_SECRET }}
          ERROR_MESSAGE: ${{ steps.run_obfuscator.outputs.error_log }}
        run: |
          export VERCEL_WEBHOOK_URL="$(printf '%s' "$VERCEL_WEBHOOK_URL" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
          export WORKER_SECRET="$(printf '%s' "$WORKER_SECRET" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
          
          echo "$ERROR_MESSAGE" > error_message.txt

          jq -n \
            --arg jid "$JOB_ID" \
            --rawfile err error_message.txt \
            '{ "jobId": $jid, "status": "FAILED", "obfuscatedCode": null, "error": $err }' > payload.json
            
          curl -f -X POST "$VERCEL_WEBHOOK_URL" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $WORKER_SECRET" \
            --data-binary @payload.json # 🎯 FIXED: Use --data-binary for files
