# .github/workflows/obfuscate.yml
name: obfuscate-on-dispatch
on:
  repository_dispatch:
    types: [prometheus-obfuscate]

jobs:
  obfuscate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: install dependencies
        run: |
          sudo apt-get update
          
          # Install LuaJIT, LuaRocks, and C build essentials
          sudo apt-get install -y luajit luarocks build-essential
          
          # CRITICAL FIX: Install LIBBSON development files
          # lua-mongo requires these to compile successfully.
          sudo apt-get install -y libbson-dev
          
          # Install the Lua MongoDB driver rock
          sudo luarocks install lua-mongo
          
      - name: run obfuscator and write to DB
        env:
          USER_CODE: ${{ github.event.client_payload.code || '' }}
          PROM_PRESET: ${{ github.event.client_payload.preset || 'Strong' }}
          JOB_ID: ${{ github.event.client_payload.job_id || '' }}
          # Pass the MongoDB secret for the Lua script to use
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: |
          chmod +x ./runner.lua || true
          luajit ./runner.lua
