# .github/workflows/obfuscate.yml
name: Prometheus Job Processor
on:
  repository_dispatch:
    types: [prometheus-job-start] # NEW EVENT TYPE

jobs:
  obfuscate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Dependencies
        run: |
          sudo apt-get update
          
          # Install LuaJIT, LuaRocks, C build essentials, and MongoDB C dependencies
          sudo apt-get install -y luajit luarocks build-essential libbson-dev libmongoc-dev
          
          # Install the Lua MongoDB driver rock
          sudo luarocks install lua-mongo
          
      - name: Run Obfuscator and Write to DB
        env:
          USER_CODE: ${{ github.event.client_payload.code || '' }}
          PROM_PRESET: ${{ github.event.client_payload.preset || 'Strong' }}
          JOB_ID: ${{ github.event.client_payload.job_id || '' }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: |
          chmod +x ./runner.lua || true
          
          # This command ensures the Lua environment path is set correctly before execution
          eval $(luarocks path) && luajit ./runner.lua

